### PR TITLE
Repository of C++ Solutions

### PR DESCRIPTION
**Pull request by SlickHackz**
Hey Tushar,

I have added many C++ solutions for famous Data Structures and Algorithms problems.
Please take time since this is a big request :(

Thanks...
Prazy

### CODE REVIEW

**Comment by nityendrasingh** [comment]
Please add this. We are ready to volunteer.

**Comment by mission-peace** [comment]
i dunno what you thinking sending 901 file reviews.

**Comment by SlickHackz** [comment]
Sorry about that... Can I create a new branch and send you request?

**Comment by SlickHackz** [comment]
Hello @nityendrasingh .. Thanks for your interest... You can also start contributing to https://github.com/SlickHackz/interview (forked from mission-peace/interview with only C++ solutions)

**Pull request closed without merging**
